// アプリケーションの全体的なレイアウトを定義するファイルです。
// Material UIのThemaProviderを使用してダークテーマを提供し、
// 全ページで使用するグローバルナビゲーションを配置します。
// AuthProviderを使用して認証状態を管理し、全ての子コンポーネントに提供します。

// import type { Metadata } from "next";
"use client";
import { ThemeProvider, createTheme } from "@mui/material/styles"
import { Box, CssBaseline } from "@mui/material";
import { AuthProvider } from "./contexts/AuthContext";

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import "./globals.css";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";


const mythema = createTheme({
  palette: {
    mode: "dark",
    primary: {
      main: "#1DA1F2",
    },
  },
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <ThemeProvider theme={mythema}>
        <CssBaseline />
        <AuthProvider>
          <body style={{ paddingTop: "80px" }}>
            <Box
              sx={{
                display: "flex",
                flexDirection: "column",
                minHeight: "100vh",
              }}
            >
              <Header />
              <Box
                component="main"
                sx={{
                  flex: 1,
                  overflow: "auto",
                  pd: 7
                }}
              >
                {children}
              </Box>
              <Footer />
            </Box>
          </body>
        </AuthProvider>
      </ThemeProvider>
    </html>
  );
}
